/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_module_soundtouch_SoundTouch */

#ifndef _Included_lib_module_soundtouch_SoundTouch
#define _Included_lib_module_soundtouch_SoundTouch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_module_soundtouch_SoundTouch
 * Method:    soundTouchCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_lib_module_soundtouch_SoundTouch_soundTouchCreate(
		JNIEnv *, jobject);

/*
 * Class:     lib_module_soundtouch_SoundTouch
 * Method:    soundTouchDestory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lib_module_soundtouch_SoundTouch_soundTouchDestory
(JNIEnv *, jobject);

/*
 * Class:     lib_module_soundtouch_SoundTouch
 * Method:    soundTouchgethVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lib_module_soundtouch_SoundTouch_soundTouchgethVersion(
		JNIEnv *, jobject);

/*
 * Class:     lib_module_soundtouch_SoundTouch
 * Method:    setPitchSemiTones
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_lib_module_soundtouch_SoundTouch_setPitchSemiTones
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     lib_module_soundtouch_SoundTouch
 * Method:    setTempoChange
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_lib_module_soundtouch_SoundTouch_setTempoChange
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     lib_module_soundtouch_SoundTouch
 * Method:    shiftingPitch
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_lib_module_soundtouch_SoundTouch_shiftingPitch
(JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     lib_module_soundtouch_SoundTouch
 * Method:    receiveSamples
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_lib_module_soundtouch_SoundTouch_receiveSamples
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     lib_module_soundtouch_SoundTouch
 * Method:    soundTouchFlushLastSamples
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lib_module_soundtouch_SoundTouch_soundTouchFlushLastSamples
  (JNIEnv *, jobject);



#ifdef __cplusplus
}
#endif
#endif
